### ISSUE TITLE
Legal issues when using ArcGIS Online image layers

### ISSUE THREAD

**Issue by joostschouppe** [Esri/arcgis-osm-editor#104]
Esri suggests using their "Online image layers" for tracing data for upload to OSM: 

"If you want to contribute to OpenStreetMap (OSM), an open and freely available database of geographic data, you can use ArcGIS Online image layers with the ArcGIS Editor for OpenStreetMap" [source](http://www.esri.com/esri-news/arcuser/fall-2014/use-arcgis-online-imagery-to-digitize-analyze-contribute)

Is this in fact legal? And if so, can I find some sort of official confirmation of this?

This [question was raised](https://help.openstreetmap.org/questions/46655/arcgis-imagery-source-tag) at the Openstreetmap Help site. Here's the [document that allows using Bing Imagery for OSM tracing](http://wiki.openstreetmap.org/w/images/d/d8/Bing_license.pdf).

Excuse me if this is off topic - but to me, it sounded like something that would be of interest for your wiki pages.

**Comment by eggwhites** [comment]
Hello joostschouppe - good question, and I can see how this might be confusing. To clarify - the article states that you can use 'ArcGIS Online Imagery' - i.e., of the provided ArcGIS Online basemaps available, you can choose the 'Imagery' basemap option.  This ArcGIS Online imagery is provided through the Esri Community Maps program (http://doc.arcgis.com/en/community-maps), and contributors understand that contributions can be accessed by the public through ArcGIS for a variety of workflows - one may be digitizing features. 

 This is not the same as Bing Imagery - ArcGIS no longer provides Bing imagery as one of its public basemap options.

**Comment by simonpoole** [comment]
@eggwhites Sorry to be stickler about this, but can you point to ToS or similar that participants in the community maps program have to agree to if ESRI themselves  cannot make a statement as to the status of data digitized from the available imagery? 

The question has actually turned up in a further different context: from a participant in the program that is unsure about the T&Cs and if it is a suitable way to provide imagery to the OSM community and I've been unable to find any document that is really clear on the matter.

**Comment by joostschouppe** [comment]
After some searching I found [a screenshot of part of the license agreement data providers sign](http://doc.arcgis.com/en/community-maps/contribute/apply.htm). I also found [this](http://communitymaps.arcgis.com/home/G-181-CM-CW_ArcGIS_Community_Maps.pdf). Read point 5: "all derivative work is owned by Esri".

**Comment by simonpoole** [comment]
@joostschouppe the good news is that point 4. actually assigns enough rights to ESRI that they could legally allow tracing by us.

**Comment by mboeringa** [comment]
> Read point 5: "all derivative work is owned by Esri".

This is a partial and inaccurate quote @joostschouppe, and thus makes it more confusing. It actually reads:

***5. Derivative Works***.
*Any derivative works (as defined under 17 USC sec.101), resultant data, or other information* ***that 
Esri creates*** *based on Data will be owned by Esri, provided that Contributor retains ownership over any portions of Data that remain separately identifiable in such works.*

Note the bold text I highlighted. Clearly, the *"owned by ESRI"* only refers to derivative works and resultant data ***that ESRI creates themselves***. The OSM community is not ESRI, so ESRI shouldn't own the derivative or resultant data created by OSM users.

In addition, since digitization of imagery and thus creating vector data, does not create ***new imagery***, but instead entirely new data that could not realistically been seen as *"portions of Data that remain separately identifiable in such works"* over which a *"Contributor retains ownership"*, I think OSM users should be fine digitizing the imagery...

**Comment by simonpoole** [comment]
@mboeringa would actually make the imagery unusable since we would have to go back to every individual source and ask them for permission.

As it stands I'm assuming that the imagerylayer composed of mulitple different sources is actually a deriviative and that ESRIs own the rights in it (as granted in 4.).

**Comment by mboeringa** [comment]
> @mboeringa would actually make the imagery unusable since we would have to go back to every individual source and ask them for permission.

Have you actually read what I wrote?

**Comment by ajturner** [comment]
I'll work with @eggwhites to look into the questions and report back to this issue.

**Comment by simonpoole** [comment]
@mboeringa yes. ESRI producing a statement that it
a) allows tracing from the imagery
b) waives all rights to the derived data 
is the best situation for us.

What is confusing you likely is that the T&Cs are an agreement between the contributors to the community maps and ESRI. NOT between ESRI and OSM, the only thing interesting for us is that ESRI does actually has the relevant rights that it can enter in to an agreement with us.

**Comment by mboeringa** [comment]
> I'll work with @eggwhites to look into the questions and report back to this issue.

@joostschouppe and @simonpoole, best to wait for this answer.

**Comment by simonpoole** [comment]
I did some digging in my mail archives and found some stuff from 2013 where permission was supposed to announced. If that did happen it clearly wasn't on any high profile OSM site/list/... If anybody is interested I can provide the name etc.

**Comment by eggwhites** [comment]
Hello All -  we at Esri are working internally to provide a full answer here. Please give us some time to get that to you. I know its important to have an answer soon.  Please stay tuned.

**Comment by eggwhites** [comment]
An update: I've learned there was much research put into this question in the past, and don't believe there should be problems with a digitizing workflow. However, we haven't published clear guidance that answers these questions you've provided - and we agree it is important to do so. So we are working on  documentation and will update this thread so you all have it. To set expectations, it likely won't be available until after the Thanksgiving holiday, as different staff in our process are travelling.

**Comment by mboeringa** [comment]
Don't forget this link to an ArcUser article @joostschouppe pointed out, that is actually highly relevant here: 

**Use ArcGIS Online Imagery to Digitize, Analyze, Contribute**
http://www.esri.com/esri-news/arcuser/fall-2014/use-arcgis-online-imagery-to-digitize-analyze-contribute

**Comment by willemarcel** [comment]
Hi @eggwhites and @mboeringa 

Furthermore the questions about the imagery ownership, it's necessary to clarify the information on that page http://downloads2.esri.com/ArcGISOnline/docs/tou_summary.pdf

It says that we need:

* Provide attribution to Esri and its data providers.
* Use with Esri software, and comply with its terms of use. If you do not have Esri software, you must purchase an ArcGIS Online subscription.

**Comment by wadnams** [comment]
Hi @eggwhites 

Is there an update on when we can expect the documentation?

Thanks.

**Comment by eggwhites** [comment]
Thanks for following up here - yes, we are working on this right now. We will update this thread as soon as we have documentation or more official guidance to share.

**Comment by marcioaguiar** [comment]
Still waiting. :smile:  It would be a great contribution if ESRI released images for tracing.

**Comment by mboeringa** [comment]
@eggwhites , it's been half a year since the last update, any news?

**Comment by mproctor1984** [comment]
Has there been a definitive answer to the discussion posted above? Specifically, I was wondering if ESRI ArcGIS Desktop and the associated imagery can be used to digitize from scratch and create vector data and create a shapefile or geodatabase feature class and then submit this to OpenStreetMap or other Open Source data storage.  The article http://www.esri.com/esri-news/arcuser/fall-2014/use-arcgis-online-imagery-to-digitize-analyze-contribute would suggest that it is OK, but I can not definitively conclude that this is indeed the case.  This question has been open for about 11 months.  Thank you in advance.

**Comment by mproctor1984** [comment]
@eggwhites and @mboeringa, is this still an active thread and/or has any resolution been found?

**Comment by cloveman** [comment]
We are reviewing the details and hope to have a response soon, sorry for the delay.

**Comment by mproctor1984** [comment]
@cloveman Thank you for taking this issue on.  If you could leave a message periodically (maybe every week or so) such that I and others on this thread can stay connected to the progress on the issue.

**Comment by mproctor1984** [comment]
@eggwhites , @mboeringa , @cloveman It has been 3 weeks in addition to the 11 months prior in regards to this issue.  An update would be appreciated even if final resolution has not been given.  OK Thanks.

**Comment by mproctor1984** [comment]
@eggwhites , @mboeringa , @cloveman It has been 5 weeks in addition to the 11 months prior in regards to this issue. An update would be appreciated even if final resolution has not been given. OK Thanks.

**Comment by mboeringa** [comment]
@mproctor1984 

To clear up a mis-understanding: I am just a user of this toolbox like you, and don't work for ESRI, so can't answer this question. I just posted here based on what I read.

The reason I have been very active in other threads as well in this repository, is because I developed a tool that depends on the Editor, and the welfare of this toolbox is thus important to me.

**Comment by mproctor1984** [comment]
Thank you for this clarification.  I am sorry for any misunderstanding.  I appreciate when people comment on related issues as it assists me in researching those issues.  I am a bit upset that ESRI has not promptly responded to this thread.  It defeats the purpose of such a forum if the ultimate authority in the given area does not participate and or clarify in a timely manner.  During the life of this thread, ESRI has went from 10.3, to 10.4, to 10.5.  I know that a legal issue may take some time to resolve but that does not prevent a contributing ESRI member from updating this thread every couple of weeks. OK Thanks.  



-----Original Message-----

**Comment by wadnams** [comment]
Hello @eggwhites and @cloveman. It is over a year since this issue was raised and is limiting our efforts on verifying and capturing data for use within OSM. Please could we have an update and status of the query. My use of ArcGIS support got me nowhere given the specialised nature of this query, so am relying on the thread for a definitive yes/no answer. Thank you.

**Comment by cloveman** [comment]
@wadnams I apologize it's taken this long. Esri's World Imagery base map has a large list of contributors that fall generally into the categories of commercial or community. Our legal team is actively reviewing each contributors agreement to ensure we don't communicate incorrect information that violates these agreements. 

As of this week, they are focused on identifying any prohibitions/restrictions in the license agreements from our commercial providers that prevents tracing vectors over the top of the imagery. And then, contributing those vectors to an organization like OSM who uses a license like the ODbL. Due to the scope of this work, it has taken much longer then expected, your patience with us is appreciated.

**Comment by wadnams** [comment]
@cloveman, appreciate the update. Thanks.

**Comment by mproctor1984** [comment]
@eggwhites ,@cloveman, at this point I would say that this discussion (thread) is no longer active.  It has been two more months or it has been a year and two months since this issue was first raised.  Still no response and still no update.  Very frustrating.

**Comment by mproctor1984** [comment]
@eggwhites ,@cloveman November of 2015 until now.  No response for the first four months of 2017.  Be professional and answer this thread, give an update, do something to validate this thread.  If the answer is you can not provide authorization, just say we can not.

**Comment by mproctor1984** [comment]
@eggwhites, @cloveman November of 2015 until now, mid July 2017. Updates/progress

**Comment by cloveman** [comment]
I want to apologize for the time it’s taken for Esri to post a response to this thread. However, as of today we have updated our “Access and Use Constraints” on our World Imagery ArcGIS Online items page.

http://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9

Of particular interest is the revamped text related to “Data Collection and Editing”.  A more detailed description under the “[use cases](https://www.arcgis.com/home/item.html?id=8e90a00a0a6845a49262e0b756f57a10)” link has been added, which in turn points to a PDF document which describes using Esri’s World Imagery basemap in the context of OSM.

**Comment by mboeringa** [comment]
@cloveman , Minor type you may wish to [correct](https://www.arcgis.com/home/item.html?id=8e90a00a0a6845a49262e0b756f57a10):

_This document provides information on the permitted **used** (--> use/uses?) for data collection and editing with the Esri World Imagery map._

**Comment by cloveman** [comment]
Thank you @mboeringa, I don't own that item page, however I shared the error with the team that does.

**Comment by mproctor1984** [comment]
@cloveman , Thank you, Thank you for your response and the efforts directed towards the issue raised by this thread.  I have not had a chance to review in detail, but I appreciate that you responded here.

**Comment by marcioaguiar** [comment]
First, thank you for the update @cloveman ! It's a big step from Esri! :+1: 

As I understand we can only upload data to OSM using Esri's World Imagery if using ArcGis? Did I understand correcly?

**Comment by jgravois** [comment]
the updated documents @cloveman shared grant the community permission to use our World Imagery to trace features and validate OSM edits even when ArcGIS tools are _not_ being used.

i opened https://github.com/osmlab/editor-layer-index/pull/358 to propose adding it to the list of canonical layers available to OpenStreetMap editors. once it lands I'll get to work on a more public announcement.

thank you **all** for your patience with us! :stuck_out_tongue_winking_eye:

as others have mentioned, this service incorporates imagery from _many_ different sources, so a sincere thanks to them as well!

> Sources: Esri, DigitalGlobe, Earthstar Geographics, CNES/Airbus DS, GeoEye, USDA FSA, USGS, Getmapping, Aerogrid, IGN, IGP, and the GIS User Community

> You can contribute your imagery to this map and have it served by Esri via the [Community Maps Program](https://livingatlas.arcgis.com/en/participate/#v=community&subTab=what-to-contribute). View the list of [Contributors for the World Imagery Map](http://esriurl.com/WorldImageryContributors).

🎉 🎉 🎉

**Comment by simonpoole** [comment]
Thanks to all for the persistence and actually getting it done!

PS: terms look OK to me for whatever that is worth.

**Comment by wadnams** [comment]
Much appreciated - thank you.

**Comment by jgravois** [comment]
we put together the blog post below to socialize this message, explain details and link to the relevant legalese.

https://blogs.esri.com/esri/arcgis/2017/08/24/world-imagery-in-osm/

_very_ happy to be able to close this issue. if anyone has additional questions in the future, don't hesitate.

**Comment by AllroadsNL** [comment]
Can you clarify this.

In the Netherlands we have aerial images from beeldmateriaal.nl 
[layers index search](http://nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/search?any_OR__title=luchtfoto&isChild='false'&fast=index)
this is open data under
http://creativecommons.org/licenses/by/4.0/deed.nl
CC 4.0 so we can not use it in Openstreetmap.
The community have a agreement with Kadaster, I en M. to use it in Openstreetmap.
https://forum.openstreetmap.org/viewtopic.php?id=57298


I see that in the [contributers list.](http://esriurl.com/WorldImageryContributors) beeldmateriaal.nl is mentioned, and the aerial on the layer look the same as we use in the Netherlands PDOK version.
Contributerlist from https://wiki.openstreetmap.org/wiki/Esri

But how can ESRI release World Imagery layer to use in Openstreetmap, when there is one that have on  the open data, a CC 4.0 licence?

Do they have a own agreement with beeldmateriaal.nl, where is mentioned, the use for Openstreetmap. ( I like to see this one.)
Or is it based on the above OSM community agreement?


World imagery not used for Openstreetmap. then also CC 4.0, says, attribution required:
Naamsvermelding verplicht: Beeldmateriaal.nl
I see no text (attribution) on the layer.

**Comment by simonpoole** [comment]
IMHO this is not a suitable topic for this repo. But just as a pointer there is at least one similar case in Germany (were imagery is available through ESRI that is not usable directly).

We suspect* that most of the imagery  (outside of what ESRI has obtained commercially to fill the gaps) has been provided to ESRI via their community maps program if so, the sources have agreed to terms that allow the providing the tiles to us. There is naturally if the resp. signees of the agreements with ESRI were actually allowed to agree to such terms, but that is slowly getting a bit much for us to verify. 

* it is naturally just as well possible that ESRI simply purchased the imagery in question.

**Comment by mboeringa** [comment]
@AllroadsNL , _for what it is worth not working for ESRI_, but having been a long term professional user of their software and happening to live in the Netherlands as well:

- Knowing the GIS world in the Netherlands, I know there is a good and generally friendly relationship between ESRI and its Dutch government clients. ESRI-NL actually hosts a series of Dutch government datasets on behalf of the government agencies, including the Kadaster aerials of the Netherlands you refer too (see http://www.esri.nl/producten/content/content/basiskaarten; http://www.esri.nl/producten/content/content/basisregistraties and e.g. http://www.arcgis.com/home/item.html?id=5c621f71daf34eef8d2973caa94a7b3b), and certainly has a big stake in facilitating this. In addition, as you also know from the Dutch OpenStreetMap forums, the Dutch OSM community in turn has contacts with the same government agencies in the Netherlands. I doubt there is really any misunderstanding about the licensing here... so I am actually wondering why you are raising this - probably non existent _from a practical point of view_ - issue here? ESRI also spend two years reviewing this legally as well, which likely included a round trip to the Dutch branch for verification...

- I am wondering why you write "CC 4.0 so we **can not use it in Openstreetmap**." while the CC4.0 
 "attribution" seems to be only relevant for the imagery layer itself, and imagery layers derived thereof, not the derived OSM vector data we create. We are not *image editing* in OSM creating a new imagery layer from this World Imagery, we are *creating vector data from it*. And CC4.0 allows a lot of freedom for creating derivative products, if I read the terms well. It would be different if the "data" being made available was not an imagery background layer, but true vector data for an OSM "import"...

- As to attribution, the World Imagery and other basemap layers do show basic attribution in ESRI's own software packages when viewed. So yes, at least part of attribution is taken care of when used in ESRI's own software (as far as possible).

- However, from a practical point of view, since the World Imagery layer is a hotchpotch of possibly hundreds of different sources, showing all attributions at the same time would plaster your screen (of course, with an imagery layer, only a few sources at a time are relevant when viewing a specific area, and those are generally shown or included as text object on print layouts in ESRI's software as well).

- As to the technical site of attribution, I think this is also not so much an issue of this repository, but probably from the editor applications, like iD and JOSM. At least in ArcGIS, the attribution is not included in the imagery itself, but as vector text overlay that is somewhat configurable in e.g. a print layout, so it can be moved and positioned to an appropriate location on a e.g. a paper map.

**Comment by jgravois** [comment]
fwiw, back in september the iD maintainers helped me put together an enhancement to display imagery metadata selectively that landed in `v2.4.2`

![screenshot 2017-09-11 09 54 10](https://user-images.githubusercontent.com/3011734/30286693-46b2d0e8-96d7-11e7-8bf1-3ba32f941907.png)

https://github.com/openstreetmap/iD/pull/4335

**Comment by simonpoole** [comment]
@mboeringa I had actually written a longer response before I had realized on which repo the question had been asked, the short version

- the imagery sources are naturally free to make whatever agreements they want with ESRI, and it simply is none of our business, as long as we are reasonably sure that they have clarified this
- CC BY is a) not an attribution only licence and b) very restrictive (yes BY, not BY-SA), that is why we require a special waiver from such sources when using them directly in OSM.

If  a CC BY licence applies to digitizing is impossible to answer in general, it really depends on which jurisdiction we are looking at and so on. So better safe than sorry.

**Comment by mboeringa** [comment]
> b) very restrictive

@simonpoole There is 'restrictive' in the sense of 

1) **... what you can do with it**, which actually seems _highly_ liberal for CC BY 4.0:

_"You are free to: 
'**Share** — copy and redistribute the material in any medium or format.'
'**Adapt** — remix, transform, and build upon the material for any purpose, even commercially.'"_

I mean, how much more free could this part of the license be?

2) **...what obligations there are for attribution.**

To me, I think you mainly refer to 2), as 1) is as about as liberal as I can think of, but 2) gives a bit of an administrative burden.

https://creativecommons.org/licenses/by/4.0/deed.en

**Comment by simonpoole** [comment]
You left out
`    No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

Which sounds harmless but isn't, see 2.a.5.B for the actual text, and yes I spent enough time discussing this with CC representatives to know how it intended to work.

`

**Comment by mboeringa** [comment]
So, fair enough, there is also 'restrictive' in the sense of 

3) **... what you can do to legally protect your derivative (and intellectual) work**, which indeed seems limited in CC BY 4.0...

4) ?

Still, if you say "very restrictive", it would be good specify in what sense to avoid confusion and generalizing to all aspects of the license... which seems inappropriate.

> I spent enough time discussing this with CC representatives to know how it intended to work.

No doubts ;-)

**Comment by simonpoole** [comment]
"more restrictive"  well particularly when applied to data it is more restrictive than say the ODbL, a share-alike licence, as CC BY applies to all kind of derivatives ("adopted material" in CC parlance) . Share-alike licences are hated because they force you to licence derivates on the same terms as you received them, CC BY just doesn't explicitly say that, but essentially boils down to the same.

So, enough spamming of Esris repo.
