### ISSUE TITLE
Empty tags values when using "Load OSM file"

### ISSUE THREAD

**Issue by Gianfra** [Esri/arcgis-osm-editor#132]
Hello, 
I need to analyze OSM data and I tried to import a file containing the history of OSM into ArcGIS.
While the process looks successful  I have a large amount of fields dedicated to tag-values that are empty. I check "Add OSM tag keys to schema(optional)", I got several fields for all tags in the area but the fields are empty.
As an example this element (https://www.openstreetmap.org/node/1014548022) comes with no tags at all while a “traffic_calming(tag value)” field has been created but filled with -Null- values only.
I am using ArcCatalog 10.2.2.

Thank you

**Comment by ThomasEmge** [comment]
This is the expected behavior. As the parameter is suggesting you are modifying the target schema. Discovering the tags and adjusting the schema on-the-fly is slowing down the loading process for larger datasets. All the tags do exist after loading and are immediately accessible within the editing environment. In order to store the tag values in the fields, you need to run the 'OSM Attribute Selector' tool to fill the osm_* fields with values.
If you are doing this more than once it is recommended to create a geoprocessing model as we have done with the "Download, Extract and Symbolize OSM Data" model tool.

- Thomas
