### ISSUE TITLE
Adding tag 

### ISSUE THREAD

**Issue by semm1968** [Esri/arcgis-osm-editor#169]
I want to import a tag called „de:amtlicher_gemeindeschluessel“ (identifier for german administrative boundaries) with the Load OSM File tool (Version 10.5).

The import runs without problems, the field is named "de:amtlicher_gemeindeschluessel(tag value)" but the value is <NULL>.  In the import file the value is set for example "04011000" für Bremen.
Maybe there’s a problem with the colon in the tag? 

Tim

**Comment by ThomasEmge** [comment]
Tim,

"de:amtlicher_gemeindeschluessel (tag value)" is the alias for the field. Due to the field restrictions for databases with respect to special characters the actual field name and the alias name are different. When you use the "Attribute Selector" tool against the layer then you might encounter some refresh issues with the attribute table appearing empty but the values should be there.
In case you just used the "load OSM file" tool and specified the "de:amtlicher_gemeindeschluessel" under schema then you just created the field but the values are not automatically populated. Run the 'attribute selector' in a second step or combine both, the loading and the attribute extraction, in a model and then execute the model.

- Thomas
