### ISSUE TITLE
geoprocessing fails for the OSM File Loader (Load Only) tool.

### ISSUE THREAD

**Issue by amalask** [Esri/arcgis-osm-editor#188]
@ThomasEmge

I don't know if this again some computer specific issue, but after installing ArcGIS for Desktop 10.6 + 64 bit background geoprocessing, and subsequently the install of the OSM Editor for 64 bit, background geoprocessing fails for the OSM File Loader (Load Only) tool.

I see the process starting up, but almost immediately finishing with the green mark of "success", but nothing is actually loaded into the target geodatabase.

If I disable background geoprocessing, the tool works as expected, and does create the Feature Classes with all the data. It just fails with background geoprocessing.

I fully uninstalled and reinstalled the 64 bit background geoprocessing component, and the OSM Editor as well, making sure I reinstalled the OSM Editor after installing the 64 bit background geoprocessing component, however all to no avail.

I did notice one other small anomaly, that the HTML Help page being opened after the OSM Editor install, still listed ArcGIS 10.5 instead of 10.6. However, I guess this is just an oversight to update the HTML page for the new 10.6 install...

**Comment by ThomasEmge** [comment]
@amalask 
The content in the HTML page is an oversight and I'll put in a request with the install team.

If possible, could you please post the geoprocessing messages from the 'successful' run. I just tried with the official installer and so far it looks ok on our office machines.

**Comment by mboeringa** [comment]
@ThomasEmge , 

@amalask literally copy&pasted my entire message from this other thread (#187) I started, only changing title. 

Apparently, @amalask has the same issue...

Anyway, as to the "successfull" run, _there isn't one for 64 bit background geoprocessing_, the successfull run was with foreground geoprocessing. The failure is with 64 bit background geoprocessing enabled. As I wrote, I correctly installed the 64 bit background processing, and the 64 bit Editor for background processing. Uninstalling and re-installing did not help.

I have now also verified that some other NON-OSM EDITOR (!) tools do run successfully with 64 bit background geoprocessing on my machine, so it does seem an issue isolated to the **OSM File Loader (Load Only)** tool. The **Load OSM File** tool by the way, shows the same behavior, and also fails, so it may affect all the tools of the Editor.

Just to exclude some stuff, I even installed the **ArcGIS (Desktop, Engine) Background Geoprocessing 64-bit Arcpy Exit and Shutdown Patch** (https://support.esri.com/en/Products/Desktop/arcgis-desktop/arcmap/10-6#downloads?id=7579), that is actually supposed to be a Windows 7 fix only (I run Win10) for another issue related to arcpy, but since it involved the background processing, and was made available after the 10.6 release, I thought I might give it a try. It did not make a difference though, the background geoprocessing still failed.

The one thing I did not yet try is to uninstall the 64 bit background geoprocessing and 64 Editor, and than reinstall the 32 bit Editor and enable ordinary 32 bit background geoprocessing. I may give that a try next.

Marco

**Comment by ThomasEmge** [comment]
@mboeringa Hmm, I am loading Austria right now and it is still going strong. After reading the issue this morning I uninstalled the editor, cleaned out the configurations files, and did a reinstall with the official release. 
Could you please send me a copy of the messages for the 64bit geoprocessing run.

**Comment by mboeringa** [comment]
@ThomasEmge ,

Unfortunately, a totally uninformative message in the geoprocessing history for the background geoprocessing run, as you can see... 

It fails immediately, however, doesn't report an error at all! In fact, it shows "Succeeded" when the background processing popup reports the end after less than a second, even though inspecting the target File Geodatabase shows nothing has happened...

![afbeelding](https://user-images.githubusercontent.com/7635726/36116049-4777cb6e-1035-11e8-88fe-b250f3a2593d.png)

**Comment by mboeringa** [comment]
@ThomasEmge 

Hmm... could I have a failed install? I both uninstalled and re-installed twice, but I now notice the DLL's listed as 1-9-2017? Is that right, Thomas? Shouldn't those list 2018?

![afbeelding](https://user-images.githubusercontent.com/7635726/36116335-207e8cfe-1036-11e8-8822-cfdfae97e931.png)

**Comment by ThomasEmge** [comment]
I don't think so, I have the same dates. I also tried to load with German OS settings and it is still working for me.

**Comment by mboeringa** [comment]
@ThomasEmge.

I have now uninstalled both the 64 bit version of the Editor and 64 bit background processing. If I subsequently re-install the 32 bit version of the Editor, and start an import using the **OSM File Loader (Load Only)** tool and background processing enabled, it works! The tool properly runs and loads the data without a hitch.

So only the 64 bit version is failing. Again note that I **_was_** able to use 64 bit background processing with other non-Editor system tools of ArcGIS. So only the Editor based tools seems to fail in the 64 bit environment on my machine.

**Comment by ThomasEmge** [comment]
If this is still an issue, please reopen.

**Comment by arfisk** [comment]
I just encountered the same problem: trying to load an OSM file using ARC Editor seems to do nothing. I ended up trying the same approach as above, and reverting to the 32 bit version.
I did encounter an additional clue: I tried disabling background processing, but Arcmap warned me that a background process needed to complete first.
It may be that the script is working, but that it's chugging away in the background on a large file with little outward sign of activity (eg the ticker tape message). That would explain why the apparent workaround is to disable background processing.
Running the 32 bit version of the load script, I found the only indication of activity was the message updates in the results window (which may not have been checked until an error gets flagged).  If this is the case, then the issue becomes one of improved visibility of activity.
I haven't tried the 64 bit version again.
