### ISSUE TITLE
extra characters inserted in "Select by Attributes" WHERE options 

### ISSUE THREAD

**Issue by OneHwang** [Esri/arcgis-osm-editor#96]
After using the "Load osm" and "OSM Attribute Selector" tools, if I open a "Select by Attributes" window, the list of available WHERE fields show "osm_" before the key. Example: instead of cycleway, I have osm_cycleway. Also, "_58_" seems to replace ":" Example: osm_cycleway_58_left instead of cycleway:left.

**Comment by mboeringa** [comment]
> After using the "Load osm" and "OSM Attribute Selector" tools, if I open a "Select by Attributes" window, the list of available WHERE fields show "osm_" before the key. Example: instead of cycleway, I have osm_cycleway. Also, "58" seems to replace ":" Example: osm_cycleway_58_left instead of cycleway:left.

This is by design. Database field names can *not* contain a ":" character, hence it is replaced by its (ASCII?) index number. Also, the "-" char (much less common in OSM key names), is similarily replaced by "_45_".

Yes, it also prepends the "osm_" to field names. It helps distinguishing the default set of OSM keys the tool always extracts (e.g. "highway", "railway", "building"), from fields extracted by the **OSM Attribute Selector** tool. I actually use this information heavily in my ArcGIS Renderer...

So you need to adjust you SQL statements, like in a layer file's Definition Query, to deal with this. Not a big issue though, you just need to be aware of this.

The tools do set a proper alias though, to make the fields more easily recognizable.

**Comment by OneHwang** [comment]
@mboeringa thanks!
